services:
  # ----------------------
  # Backend: Server (Prod)
  # ----------------------
  - type: web
    name: thearchitect-server-prod
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    plan: starter
    domains:
      - api.incharge-ai.com
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: REDIS_URL
        sync: false
      - key: PINECONE_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false

  # ----------------------
  # Widget (Prod)
  # ----------------------
  - type: web
    name: thearchitect-widget-prod
    env: static
    rootDir: client-widget
    buildCommand: npm install && npm run build:production
    staticPublishPath: dist
    domains:
      - widget.incharge-ai.com
    envVars:
      - key: VITE_API_BASE
        value: https://api.incharge-ai.com/api

  # ----------------------
  # Playground (Prod)
  # ----------------------
  - type: web
    name: thearchitect-playground-prod
    env: static
    rootDir: client-playground
    buildCommand: npm install && npm run build:production
    staticPublishPath: dist
    domains:
      - playground.incharge-ai.com
    envVars:
      - key: VITE_API_BASE
        value: https://api.incharge-ai.com/api
